# -*- coding: utf-8 -*-
"""CodeAlpha_Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRkzX4h5usu_SAP1CbAYOMN-rIzP0gE7
"""

import re
import random
import datetime

class ChatBot:
    def __init__(self):
        self.user_name = None
        self.history = []
        self.responses = {
            "greeting": ["Hello! 👋", "Hi there! 😊", "Hey! How can I help you today?"],
            "how_are_you": ["I'm doing great, thanks for asking! How about you?"],
            "bye": ["Goodbye! 👋 Take care.", "See you later!", "Bye-bye!"],
            "name": ["I'm CodeAlpha Bot 🤖, created for my internship project."],
            "thanks": ["You're welcome! 🙏", "No problem!", "Happy to help! 😄"]
        }

    def detect_intent(self, user_input):
        """Detect intent using regex + keywords"""
        user_input = user_input.lower()

        if re.search(r"\b(hi|hello|hey)\b", user_input):
            return "greeting"
        elif re.search(r"how (are|r) (you|u)", user_input):
            return "how_are_you"
        elif re.search(r"\b(bye|goodbye|see you)\b", user_input):
            return "bye"
        elif re.search(r"\b(name|who are you)\b", user_input):
            return "name"
        elif re.search(r"\b(thanks|thank you)\b", user_input):
            return "thanks"
        elif re.search(r"\b(my name is|i am|i'm)\b", user_input):
            return "set_name"
        else:
            return "unknown"

    def get_response(self, intent, user_input):
        """Return reply based on intent"""
        if intent == "greeting":
            return random.choice(self.responses["greeting"])

        elif intent == "how_are_you":
            return self.responses["how_are_you"][0]

        elif intent == "bye":
            return random.choice(self.responses["bye"])

        elif intent == "name":
            if self.user_name:
                return f"My name is CodeAlpha Bot 🤖, and I remember yours is {self.user_name}!"
            else:
                return self.responses["name"][0]

        elif intent == "set_name":
            # Extract name from input
            match = re.search(r"(?:my name is|i am|i'm)\s+(\w+)", user_input)
            if match:
                self.user_name = match.group(1).capitalize()
                return f"Nice to meet you, {self.user_name}! 😊"
            return "Sorry, I didn’t catch your name. Can you repeat?"

        elif intent == "thanks":
            return random.choice(self.responses["thanks"])

        else:
            return random.choice([
                "Hmm 🤔 I’m not sure I understand.",
                "Can you rephrase that?",
                "Interesting! Tell me more."
            ])

    def chat(self):
        """Main chatbot loop"""
        print("🤖 CodeAlpha Chatbot is online! (Type 'bye' to exit)\n")

        while True:
            user_input = input("You: ")
            self.history.append(("You", user_input, str(datetime.datetime.now())))

            intent = self.detect_intent(user_input)
            reply = self.get_response(intent, user_input)

            print("Bot:", reply)
            self.history.append(("Bot", reply, str(datetime.datetime.now())))

            if intent == "bye":
                self.save_history()
                break

    def save_history(self):
        """Save chat history to file"""
        with open("chat_log.txt", "w") as f:
            for speaker, text, timestamp in self.history:
                f.write(f"[{timestamp}] {speaker}: {text}\n")
        print("\n📂 Chat history saved to 'chat_log.txt'.")

bot = ChatBot()
bot.chat()